//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPractice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegalHolidayDates
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Day { get; set; }
        public System.DateTime HolidayStartDate { get; set; }
        public System.DateTime HolidayFinishDate { get; set; }
        public int AddedByUserID { get; set; }
    }
}
