//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPractice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID { get; set; }
        public Nullable<bool> IsPersonel { get; set; }
        public int FirmID { get; set; }
        public int OwnerID { get; set; }
        public int TypeID { get; set; }
        public int TaskID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string EmailAddress { get; set; }
        public string Phone { get; set; }
        public string CCSINo { get; set; }
        public System.DateTime CreateAt { get; set; }
        public bool IsActive { get; set; }
        public bool IsWarehouse { get; set; }
        public System.DateTime JobStartDate { get; set; }
        public Nullable<System.DateTime> JobFinishDate { get; set; }
        public string JobFinishDescription { get; set; }
        public string IdentityNumber { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string AccountNumber { get; set; }
        public int SubeKod { get; set; }
        public int BankaKodu { get; set; }
        public Nullable<int> AdminID { get; set; }
    }
}
